###登录 login
POST {{host}}/api/user/login
Content-Type: application/json

{
  "account": "18613030352",
  "password": "123456"
}
> {%
    client.global.set("token", response.body.data.token);
%}


###部门列表 queryDeptList
POST {{host}}/api/dept/queryDeptList
Content-Type: application/json
Authorization: Bearer {{token}}

{

}

###新增部门 addDept
POST {{host}}/api/dept/addDept
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "deptName": "测试1",
  "parentId": 0,
  "sort": 1,
  "remark": "测试1"
}

###删除部门 deleteDeptByIds
POST {{host}}/api/dept/deleteDeptByIds
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "ids": [
    100
  ]
}

###更新部门 updateDept
POST {{host}}/api/dept/updateDept
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 1,
  "deptName": "测试11",
  "parentId": 0,
  "sort": 1,
  "remark": "测试",
  "createTime": "2024-04-30T14:15:32+08:00",
  "updateTime": null
}


