###登录 login
POST {{host}}/api/user/login
Content-Type: application/json

{
  "account": "18613030352",
  "password": "123456"
}
> {%
    client.global.set("token", response.body.data.token);
%}


###查询操作日志 queryOperateLogList
POST {{host}}/api/sysLog/queryOperateLogList
Content-Type: application/json
Authorization: Bearer {{token}}

{

}

###删除操作日志 deleteOperateLogByIds
POST {{host}}/api/sysLog/deleteOperateLogByIds
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "ids": []
}

###查询登录日志 queryLoginLogList
POST {{host}}/api/loginLog/queryLoginLogList
Content-Type: application/json
Authorization: Bearer {{token}}

{

}

###删除登录日志 deleteLoginLogByIds
POST {{host}}/api/loginLog/deleteLoginLogByIds
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "ids": []
}

