###登录 login
POST {{host}}/api/user/login
Content-Type: application/json

{
  "mobile": "18613030352",
  "password": "123456"
}
> {%
    client.global.set("token", response.body.data);
%}


###菜单列表 queryMenuList
GET {{host}}/api/menu/queryMenuList
Authorization: Bearer {{token}}


###新增菜单 addMenu
POST {{host}}/api/menu/addMenu
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "menuName": "test",
  "menuType": 3,
  "statusId": 1,
  "sort": 3,
  "parentId": 5,
  "menuUrl": "",
  "apiUrl": "/api/menu/updateMenu",
  "menuIcon": "",
  "remark": "test"
}

###删除菜单 deleteMenuById
POST {{host}}/api/menu/deleteMenuById
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 39
}

###更新菜单 updateMenu
POST {{host}}/api/menu/updateMenu
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 39,
  "menuName": "123",
  "menuType": 3,
  "statusId": 1,
  "sort": 3,
  "parentId": 5,
  "menuUrl": "",
  "apiUrl": "/api/menu/updateMenu",
  "menuIcon": "",
  "remark": "te123st"
}

