###登录 login
POST {{host}}/api/user/login
Content-Type: application/json

{
  "account": "18613030352",
  "password": "123456"
}
> {%
    client.global.set("token", response.body.data.token);
%}

###查询角色菜单 queryRoleMenuList
GET {{host}}/api/role/queryRoleMenuList?roleId=3
Authorization: Bearer {{token}}


###更新角色菜单 updateRoleMenuList
POST {{host}}/api/role/updateRoleMenuList
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "roleId": 3,
  "menuIds": [
    1,
    2,
    3
  ]
}

###角色列表 role_list
POST {{host}}/api/role/queryRoleList
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "current": 1,
  "pageSize": 10,
  "statusId": 2
}

###新增角色 addRole
POST {{host}}/api/role/addRole
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "roleName": "test",
  "statusId": 1,
  "sort": 1,
  "remark": "test"
}

###删除角色 deleteRoleByIds
POST {{host}}/api/role/deleteRoleByIds
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "ids": [
    3
  ]
}

###更新角色 updateRole
POST {{host}}/api/role/updateRole
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 3,
  "roleName": "tes12t",
  "statusId": 1,
  "sort": 1,
  "remark": "tes12t"
}
