
###登录 login
POST {{host}}/api/user/login
Content-Type: application/json

{
  "account": "18613030352",
  "password": "123456"
}
> {%
    client.global.set("token", response.body.data.token);
%}

###查询用户菜单 queryUserMenu
GET {{host}}/api/user/queryUserMenuList
Authorization: Bearer {{token}}


###用户列表 queryUserList
POST {{host}}/api/user/queryUserList
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "pageNo": 1,
  "pageSize": 10,
  "statusId": 1
}

###新增用户 addUser
POST {{host}}/api/user/addUser
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "mobile": "18613030112",
  "userName": "超级管理员1",
  "statusId": 1,
  "sort": 1,
  "remark": "超级管理员"
}

###删除用户 deleteUserByIds
POST {{host}}/api/user/deleteUserByIds
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "ids": [
    3
  ]
}

###更新用户 updateUser
POST {{host}}/api/user/updateUser
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 3,
  "mobile": "18613030112",
  "userName": "123",
  "statusId": 1,
  "sort": 1,
  "remark": "超级管理员"
}


###根据用户id查询用户与角色关糸 queryUserRoleList
GET {{host}}/api/user/queryUserRoleList?userId=2
Authorization: Bearer {{token}}


###更新用户与角色关糸 updateUserRoleList
POST {{host}}/api/user/updateUserRoleList
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": 17,
  "roleId": []
}

