# 配置服务器的网络地址和端口号
server:
  address: 127.0.0.1
  port: 6677

# MySQL数据库的连接配置
mysql:
  host: 127.0.0.1
  port: 3306
  database: simple-go
  username: root
  password: 123456

# JWT（JSON Web Token）的配置
jwt:
  accessSecret: 879037c7a4406392366bfc35d
  accessExpire: 86400

# Redis数据库的连接配置
redis:
  host: 127.0.0.1
  port: 6379
  password: 123456

# 环境变量配置,防止暴露敏感信息

# Windows
#  set MYAPP_MYSQL_HOST=127.0.0.1
#  set MYAPP_MYSQL_PASSWORD=123456
#  set MYAPP_MYSQL_PORT=3306
#  set MYAPP_REDIS_HOST=127.0.0.1
#  set MYAPP_REDIS_PASSWORD=123456
#  set MYAPP_REDIS_PORT=6379

# Linux/Mac
#  export MYAPP_MYSQL_HOST=127.0.0.1
#  export MYAPP_MYSQL_PASSWORD=123456
#  export MYAPP_MYSQL_PORT=3306
#  export MYAPP_REDIS_HOST=127.0.0.1
#  export MYAPP_REDIS_PASSWORD=123456
#  export MYAPP_REDIS_PORT=6379


# 如果是使用goland启动，则需要配置一下
#MYAPP_MYSQL_HOST=127.0.0.1;MYAPP_MYSQL_PASSWORD=123456;MYAPP_MYSQL_PORT=3306;MYAPP_REDIS_HOST=127.0.0.1;MYAPP_REDIS_PASSWORD=123456;MYAPP_REDIS_PORT=6379