// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	system2 "github.com/feihua/simple-go/internal/controller/system"
	"github.com/feihua/simple-go/internal/dao/system"
	"github.com/feihua/simple-go/internal/model"
	"github.com/feihua/simple-go/internal/router"
	"github.com/feihua/simple-go/internal/service/system/dept"
	"github.com/feihua/simple-go/internal/service/system/dict_data"
	"github.com/feihua/simple-go/internal/service/system/dict_type"
	"github.com/feihua/simple-go/internal/service/system/login_log"
	"github.com/feihua/simple-go/internal/service/system/menu"
	"github.com/feihua/simple-go/internal/service/system/notice"
	"github.com/feihua/simple-go/internal/service/system/operate_log"
	"github.com/feihua/simple-go/internal/service/system/post"
	"github.com/feihua/simple-go/internal/service/system/role"
	"github.com/feihua/simple-go/internal/service/system/user"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func initApp() *gin.Engine {
	db := model.Init()
	userDao := system.NewUserDao(db)
	userService := user.NewUserServiceImpl(userDao)
	userController := system2.NewUserController(userService)
	roleDao := system.NewRoleDao(db)
	roleService := role.NewRoleServiceImpl(roleDao)
	roleController := system2.NewRoleController(roleService)
	menuDao := system.NewMenuDao(db)
	menuService := menu.NewMenuServiceImpl(menuDao)
	menuController := system2.NewMenuController(menuService)
	loginLogDao := system.NewLoginLogDao(db)
	loginLogService := login_log.NewLoginLogServiceImpl(loginLogDao)
	loginLogController := system2.NewLoginLogController(loginLogService)
	operateLogDao := system.NewOperateLogDao(db)
	operateLogService := operate_log.NewOperateLogServiceImpl(operateLogDao)
	operateLogController := system2.NewOperateLogController(operateLogService)
	dictDataDao := system.NewDictDataDao(db)
	dictDataService := dict_data.NewDictDataServiceImpl(dictDataDao)
	dictDataController := system2.NewDictDataController(dictDataService)
	dictTypeDao := system.NewDictTypeDao(db)
	dictTypeService := dict_type.NewDictTypeServiceImpl(dictTypeDao)
	dictTypeController := system2.NewDictTypeController(dictTypeService)
	noticeDao := system.NewNoticeDao(db)
	noticeService := notice.NewNoticeServiceImpl(noticeDao)
	noticeController := system2.NewNoticeController(noticeService)
	deptDao := system.NewDeptDao(db)
	deptService := dept.NewDeptServiceImpl(deptDao)
	deptController := system2.NewDeptController(deptService)
	postDao := system.NewPostDao(db)
	postService := post.NewPostServiceImpl(postDao)
	postController := system2.NewPostController(postService)
	engine := router.Init(userController, roleController, menuController, loginLogController, operateLogController, dictDataController, dictTypeController, noticeController, deptController, postController)
	return engine
}
