// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	dept2 "github.com/feihua/simple-go/internal/controller/dept"
	dict2 "github.com/feihua/simple-go/internal/controller/dict"
	log2 "github.com/feihua/simple-go/internal/controller/log"
	menu2 "github.com/feihua/simple-go/internal/controller/menu"
	role2 "github.com/feihua/simple-go/internal/controller/role"
	user2 "github.com/feihua/simple-go/internal/controller/user"
	"github.com/feihua/simple-go/internal/dao"
	"github.com/feihua/simple-go/internal/model"
	"github.com/feihua/simple-go/internal/router"
	"github.com/feihua/simple-go/internal/service/dept"
	"github.com/feihua/simple-go/internal/service/dict"
	"github.com/feihua/simple-go/internal/service/log"
	"github.com/feihua/simple-go/internal/service/menu"
	"github.com/feihua/simple-go/internal/service/role"
	"github.com/feihua/simple-go/internal/service/user"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func initApp() *gin.Engine {
	db := model.Init()
	userDao := dao.NewUserDao(db)
	userRoleDao := dao.NewUserRoleDao(db)
	menuDao := dao.NewMenuDao(db)
	roleDao := dao.NewRoleDao(db)
	userService := user.NewUserServiceImpl(userDao, userRoleDao, menuDao, roleDao)
	userController := user2.NewUserController(userService)
	roleMenuDao := dao.NewRoleMenuDao(db)
	roleService := role.NewRoleServiceImpl(roleDao, menuDao, roleMenuDao)
	roleController := role2.NewRoleController(roleService)
	menuService := menu.NewMenuServiceImpl(menuDao)
	menuController := menu2.NewMenuController(menuService)
	logDao := dao.NewLogDao(db)
	logService := log.NewLogServiceImpl(logDao)
	logController := log2.NewLogController(logService)
	dictDao := dao.NewDictDao(db)
	dictService := dict.NewDictServiceImpl(dictDao)
	dictController := dict2.NewDictController(dictService)
	deptDao := dao.NewDeptDao(db)
	deptService := dept.NewDeptServiceImpl(deptDao)
	deptController := dept2.NewDeptController(deptService)
	engine := router.Init(userController, roleController, menuController, logController, dictController, deptController)
	return engine
}
