// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/feihua/simple-go/internal/controller/system"
	system2 "github.com/feihua/simple-go/internal/dao/system"
	"github.com/feihua/simple-go/internal/model"
	"github.com/feihua/simple-go/internal/router"
	"github.com/feihua/simple-go/internal/service/system/dept"
	"github.com/feihua/simple-go/internal/service/system/dict"
	"github.com/feihua/simple-go/internal/service/system/log"
	"github.com/feihua/simple-go/internal/service/system/menu"
	"github.com/feihua/simple-go/internal/service/system/role"
	"github.com/feihua/simple-go/internal/service/system/user"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func initApp() *gin.Engine {
	db := model.Init()
	userDao := system2.NewUserDao(db)
	userRoleDao := system2.NewUserRoleDao(db)
	menuDao := system2.NewMenuDao(db)
	roleDao := system2.NewRoleDao(db)
	userService := user.NewUserServiceImpl(userDao, userRoleDao, menuDao, roleDao)
	userController := system.NewUserController(userService)
	roleMenuDao := system2.NewRoleMenuDao(db)
	roleService := role.NewRoleServiceImpl(roleDao, menuDao, roleMenuDao)
	roleController := system.NewRoleController(roleService)
	menuService := menu.NewMenuServiceImpl(menuDao)
	menuController := system.NewMenuController(menuService)
	logDao := system2.NewLogDao(db)
	logService := log.NewLogServiceImpl(logDao)
	logController := system.NewLogController(logService)
	dictDao := system2.NewDictDao(db)
	dictService := dict.NewDictServiceImpl(dictDao)
	dictController := system.NewDictController(dictService)
	deptDao := system2.NewDeptDao(db)
	deptService := dept.NewDeptServiceImpl(deptDao)
	deptController := system.NewDeptController(deptService)
	engine := router.Init(userController, roleController, menuController, logController, dictController, deptController)
	return engine
}
